services:
  gogin:
    image: demo/go
    init: true
    restart: "no"
    build:
      context: ./app
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ping || exit 1
      interval: 1m30s
      timeout: 2s
      retries: 3
      start_period: 40s
    environment:
      - GIN_MODE=release
    ports:
      - "8080:8080"
    networks:
      - app-tier
    profiles:
      - test      

  mongodb:
    image: 'bitnami/mongodb:latest'
    networks:
      - app-tier
    restart: "no"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - mongo-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: example
    profiles:
      - test

  mongo-express:
    image: mongo-express
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app-tier
    profiles:
      - test

networks:
  app-tier:
    driver: bridge

volumes:
  mongo-data: