services:
  gogin:
    image: demo/go
    init: true
    restart: "no"
    build:
      context: ./app
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ping || exit 1
      interval: 1m30s
      timeout: 2s
      retries: 3
      start_period: 40s
    environment:
      - GIN_MODE=release
    ports:
      - "8080:8080"
    profiles:
      - test
